[package]
name = "rust_structs_algos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
rand = "0.8.5"
async-recursion = "1.1.0"
rayon = "1.8"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
